### ISSUE TITLE
roomで放置していると落ちる．

### ISSUE THREAD

**Issue by chigichan24** [cyder/SyncPod-Android#200]
websocketがどうこうとかほざいている．
```
04-15 17:11:52.474 11502-11535/com.cyder.atsushi.youtubesync.develop.debug E/AndroidRuntime: FATAL EXCEPTION: EventLoop
    Process: com.cyder.atsushi.youtubesync.develop.debug, PID: 11502
    io.reactivex.exceptions.UndeliverableException: java.net.SocketTimeoutException: timeout
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
        at com.cyder.atsushi.youtubesync.repository.RoomDataRepository$joinRoom$1$3.invoke(RoomDataRepository.kt:42)
        at com.cyder.atsushi.youtubesync.repository.RoomDataRepository$joinRoom$1$3.invoke(RoomDataRepository.kt:21)
        at com.hosopy.actioncable.Subscription.notifyFailed$actioncable_client_kotlin_main(Subscription.kt:62)
        at com.hosopy.actioncable.Subscriptions.notifyFailed$actioncable_client_kotlin_main(Subscriptions.kt:58)
        at com.hosopy.actioncable.Consumer$4.invoke(Consumer.kt:64)
        at com.hosopy.actioncable.Consumer$4.invoke(Consumer.kt:18)
        at com.hosopy.actioncable.Connection$webSocketListener$1$onFailure$1.doResume(Connection.kt:168)
        at com.hosopy.actioncable.Connection$webSocketListener$1$onFailure$1.invoke(Connection.kt)
        at com.hosopy.actioncable.Connection$webSocketListener$1$onFailure$1.invoke(Connection.kt:156)
        at com.hosopy.actioncable.SerializedOperationQueue$actor$1.doResume(Connection.kt:204)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.AbstractContinuation.run(AbstractContinuation.kt:31)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
        at okio.RealBufferedSource.request(RealBufferedSource.java:67)
        at okio.RealBufferedSource.require(RealBufferedSource.java:60)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
        at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110)
        at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99)
        at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
        at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153)
        at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
        at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.request(RealBufferedSource.java:67) 
        at okio.RealBufferedSource.require(RealBufferedSource.java:60) 
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) 
        at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:110) 
        at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:99) 
        at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97) 
        at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:153) 
        at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40) 
        at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by chigichan24** [comment]
`joinRoom`のCompletableでonErrorに入って落ちてるので，disposeするなどしないといけないのかなと思ってます．
